[package]
name = "server"
version = "0.1.0"
edition = "2024"

[lib]
name = "server_lib"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
tonic = "0.14"
tonic-prost = "0.14.6"
prost = "0.14"
clap = { version = "4.6.7", features = ["derive", "env"] }

[build-dependencies]
tonic-prost-build = "0.14"
